# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1292, 858)
        MainWindow.setStyleSheet("background-color:#fff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Container = QtWidgets.QWidget(self.centralwidget)
        self.Container.setGeometry(QtCore.QRect(440, 630, 400, 200))
        self.Container.setMinimumSize(QtCore.QSize(400, 200))
        self.Container.setMaximumSize(QtCore.QSize(400, 200))
        self.Container.setStyleSheet("border-radius:20px;\n"
"background-color:#f7f7f7;")
        self.Container.setObjectName("Container")
        self.loginButton_3 = QtWidgets.QPushButton(self.Container)
        self.loginButton_3.setGeometry(QtCore.QRect(80, 120, 250, 50))
        self.loginButton_3.setMinimumSize(QtCore.QSize(250, 50))
        self.loginButton_3.setMaximumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.loginButton_3.setFont(font)
        self.loginButton_3.setMouseTracking(True)
        self.loginButton_3.setTabletTracking(True)
        self.loginButton_3.setStyleSheet("QPushButton {\n"
" background-color: #5698d2;\n"
"border-radius:12px;\n"
"color:#fff;\n"
"border: 1px solid #707070;\n"
"}\n"
"QPushButton#quit_button {\n"
"   background-color: green;\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: #fff;\n"
"}\n"
"QpushButton{\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"border-width:200px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #4379a5;\n"
"   transition: background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"border:none;\n"
"")
        self.loginButton_3.setObjectName("loginButton_3")
        self.widget = QtWidgets.QWidget(self.Container)
        self.widget.setGeometry(QtCore.QRect(140, 70, 238, 27))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"       border: 1px solid #707070;\n"
"    border-radius: 4px;\n"
"    \n"
"  \n"
"   background-color: #f0f0f0;\n"
"    selection-background-color: #cce5ff; /* Color when text is selected */\n"
"\n"
"   padding:2px;\n"
"\n"
"    /* Placeholder text */\n"
"    placeholder-text-color: #999999;\n"
"\n"
"\n"
"    /* Hover and focus effects */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #4d90fe;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.Container)
        self.widget1.setGeometry(QtCore.QRect(20, 20, 357, 35))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.chartType_comboBox = QtWidgets.QComboBox(self.widget1)
        self.chartType_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.chartType_comboBox.setStyleSheet("QComboBox {\n"
"\n"
"\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f9f9f9;\n"
"    color: #333333;\n"
"    font: 14px \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    image: url(:/Icon/icons8-arrow-down-16.png);\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #cccccc;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background: #e6e6e6;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down-arrow-icon.png); /* Replace with your own down arrow icon */\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #cccccc;\n"
"    selection-background-color: #e6e6e6;\n"
"    selection-color: #333333;\n"
"}\n"
"")
        self.chartType_comboBox.setObjectName("chartType_comboBox")
        self.chartType_comboBox.addItem("")
        self.chartType_comboBox.addItem("")
        self.chartType_comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.chartType_comboBox)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 30, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 830, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(40, 120, 1216, 492))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginButton = QtWidgets.QPushButton(self.widget2)
        self.loginButton.setMinimumSize(QtCore.QSize(150, 30))
        self.loginButton.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.loginButton.setFont(font)
        self.loginButton.setMouseTracking(True)
        self.loginButton.setTabletTracking(True)
        self.loginButton.setStyleSheet("QPushButton {\n"
" background-color: #10cc94;\n"
"border-radius:12px;\n"
"color:#fff;\n"
"}\n"
"QPushButton#quit_button {\n"
"   background-color: green;\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: #fff;\n"
"}\n"
"QpushButton{\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"border-width:200px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #0a9c73;\n"
"   transition: background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"border:none;\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.add_to_cart_button_4 = QtWidgets.QPushButton(self.widget2)
        self.add_to_cart_button_4.setMinimumSize(QtCore.QSize(150, 30))
        self.add_to_cart_button_4.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.add_to_cart_button_4.setFont(font)
        self.add_to_cart_button_4.setMouseTracking(True)
        self.add_to_cart_button_4.setTabletTracking(True)
        self.add_to_cart_button_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_to_cart_button_4.setStyleSheet("QPushButton {\n"
" background-color: #F88379;\n"
"border-radius:12px;\n"
"color:#fff;\n"
"}\n"
"QPushButton#quit_button {\n"
"   background-color: green;\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: #fff;\n"
"}\n"
"QpushButton{\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"border-width:200px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #E5676B;\n"
"   transition: background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"border:none;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/Shop/Shoppingcart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_to_cart_button_4.setIcon(icon)
        self.add_to_cart_button_4.setIconSize(QtCore.QSize(22, 22))
        self.add_to_cart_button_4.setObjectName("add_to_cart_button_4")
        self.horizontalLayout.addWidget(self.add_to_cart_button_4)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(130, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit.setMinimumSize(QtCore.QSize(600, 450))
        self.lineEdit.setMaximumSize(QtCore.QSize(700, 450))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    /* Background and border */\n"
"    border: 2px solid #707070;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: #f0f0f0;\n"
"    selection-background-color: #cce5ff; /* Color when text is selected */\n"
"\n"
"    /* Text color and font */\n"
"    color: #333333;\n"
"    font-size: 16px;\n"
"    font-family: Arial, sans-serif;\n"
"\n"
"    /* Placeholder text */\n"
"    placeholder-text-color: #999999;\n"
"\n"
"    /* Align text to the top */\n"
"    padding-top: 5px; /* Adjust as needed */\n"
"    padding-bottom: 5px; /* Adjust as needed */\n"
"    alignment: align-top; /* Align text to the top */\n"
"\n"
"    /* Hover and focus effects */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #4d90fe;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(600, 450))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(700, 450))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    /* Background and border */\n"
"    border: 2px solid #707070;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: #f0f0f0;\n"
"    selection-background-color: #cce5ff; /* Color when text is selected */\n"
"\n"
"    /* Text color and font */\n"
"    color: #333333;\n"
"    font-size: 16px;\n"
"    font-family: Arial, sans-serif;\n"
"\n"
"    /* Placeholder text */\n"
"    placeholder-text-color: #999999;\n"
"\n"
"    /* Align text to the top */\n"
"    padding-top: 5px; /* Adjust as needed */\n"
"    padding-bottom: 5px; /* Adjust as needed */\n"
"    alignment: align-top; /* Align text to the top */\n"
"\n"
"    /* Hover and focus effects */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #4d90fe;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loginButton_2 = QtWidgets.QPushButton(self.widget2)
        self.loginButton_2.setMinimumSize(QtCore.QSize(150, 30))
        self.loginButton_2.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.loginButton_2.setFont(font)
        self.loginButton_2.setMouseTracking(True)
        self.loginButton_2.setTabletTracking(True)
        self.loginButton_2.setStyleSheet("QPushButton {\n"
" background-color: #10cc94;\n"
"border-radius:12px;\n"
"color:#fff;\n"
"}\n"
"QPushButton#quit_button {\n"
"   background-color: green;\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: #fff;\n"
"}\n"
"QpushButton{\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"border-width:200px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #0a9c73;\n"
"   transition: background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"border:none;\n"
"")
        self.loginButton_2.setObjectName("loginButton_2")
        self.horizontalLayout_3.addWidget(self.loginButton_2)
        self.add_to_cart_button_5 = QtWidgets.QPushButton(self.widget2)
        self.add_to_cart_button_5.setMinimumSize(QtCore.QSize(150, 30))
        self.add_to_cart_button_5.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.add_to_cart_button_5.setFont(font)
        self.add_to_cart_button_5.setMouseTracking(True)
        self.add_to_cart_button_5.setTabletTracking(True)
        self.add_to_cart_button_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_to_cart_button_5.setStyleSheet("QPushButton {\n"
" background-color: #F88379;\n"
"border-radius:12px;\n"
"color:#fff;\n"
"}\n"
"QPushButton#quit_button {\n"
"   background-color: green;\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: #fff;\n"
"}\n"
"QpushButton{\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"border-width:200px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #E5676B;\n"
"   transition: background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"border:none;\n"
"")
        self.add_to_cart_button_5.setIcon(icon)
        self.add_to_cart_button_5.setIconSize(QtCore.QSize(22, 22))
        self.add_to_cart_button_5.setObjectName("add_to_cart_button_5")
        self.horizontalLayout_3.addWidget(self.add_to_cart_button_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(130, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PlagiarismChecker"))
        self.loginButton_3.setText(_translate("MainWindow", "Check Plagiarism"))
        self.label_6.setText(_translate("MainWindow", "Chunk Size:"))
        self.label_5.setText(_translate("MainWindow", "Select Scheduling Algorithm:"))
        self.chartType_comboBox.setItemText(0, _translate("MainWindow", "Round Robin"))
        self.chartType_comboBox.setItemText(1, _translate("MainWindow", "Shortest Job Next"))
        self.chartType_comboBox.setItemText(2, _translate("MainWindow", "Priority Scheduling"))
        self.label_7.setText(_translate("MainWindow", "Egg Plagiarism Checker"))
        self.label_8.setText(_translate("MainWindow", "Developed by:  Buenaventura - Santos - Tan - Tiamzon"))
        self.loginButton.setText(_translate("MainWindow", "Open File "))
        self.add_to_cart_button_4.setText(_translate("MainWindow", "Clear"))
        self.label.setText(_translate("MainWindow", "Word Count:"))
        self.label_2.setText(_translate("MainWindow", "0000"))
        self.loginButton_2.setText(_translate("MainWindow", "Open File "))
        self.add_to_cart_button_5.setText(_translate("MainWindow", "Clear"))
        self.label_3.setText(_translate("MainWindow", "Word Count:"))
        self.label_4.setText(_translate("MainWindow", "0000"))
import logo_rc
